// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"auth\"><div class=\"row h-100\"><div class=\"col-lg-5 col-12\"><div id=\"auth-left\"><div class=\"auth-logo\"><a href=\"#\"><img src=\"/assets/compiled/png/logo.png\" alt=\"Logo\"></a></div><h1 class=\"auth-title\">Log in.</h1><p class=\"auth-subtitle mb-5\">Please use your credentials to log in</p><form action=\"/login\" method=\"POST\"><div class=\"form-group position-relative has-icon-left mb-4\"><input name=\"username\" type=\"text\" class=\"form-control form-control-xl\" placeholder=\"Username\"><div class=\"form-control-icon\"><i class=\"bi bi-person\"></i></div></div><div class=\"form-group position-relative has-icon-left mb-4\"><input name=\"password\" type=\"password\" class=\"form-control form-control-xl\" placeholder=\"Password\"><div class=\"form-control-icon\"><i class=\"bi bi-shield-lock\"></i></div></div><div class=\"form-check form-check-lg d-flex align-items-end\"><input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\"> <label class=\"form-check-label text-gray-600\" for=\"flexCheckDefault\">Keep me logged in</label></div><button class=\"btn btn-primary btn-block btn-lg shadow-lg mt-5\">Log in</button></form><div class=\"text-center mt-5 text-lg fs-4\"><p class=\"text-gray-600\">Don't have an account? <a href=\"auth-register.html\" class=\"font-bold\">Sign up</a>.</p><p><a class=\"font-bold\" href=\"auth-forgot-password.html\">Forgot password?</a>.</p></div></div></div><div class=\"col-lg-7 d-none d-lg-block\"><div id=\"auth-right\"></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
